### PR TITLE
Pointed docs links to the new docs

### PR DESCRIPTION
**Pull request by AlexejPenner**

### CODE REVIEW

**Review by strickvl — CHANGES_REQUESTED** [review]
Not sure I understand these changes... you've changed it all to this pattern:

```
https://docs.zenml.io/stack-components/model-deployers/seldon
```

whereas it should be:

```
https://docs.zenml.io/stack-components/component-guide/model-deployers/seldon
```

**Comment by strickvl** [comment]
(for the stack components at least...) there will be other patterns ofc

**Review by strickvl — APPROVED** [review]
Approving this now, knowing what I know following last week's changes :)

**Review by htahir1 — APPROVED** [review]

**Comment by htahir1** [comment]
lets merge thsi right @AlexejPenner ?

**Review by AlexejPenner — COMMENTED** [review]
:seal:

**Pull request merged**
