### PR TITLE
Update ZenML and fix the index used to fetch the last pipeline run

### PR DESCRIPTION
**Pull request by stefannica**

### CODE REVIEW

**Review by htahir1 — COMMENTED** [review]
I suppose this only makes sense when we upgrade the requirements.txt to have ZenML 0.35.0

**Comment by stefannica** [comment]
> I suppose this only makes sense when we upgrade the requirements.txt to have ZenML 0.35.0

Done

**Review by htahir1 — APPROVED** [review]
If we have run all of these and checked it works, then im happy with it!

**Comment by stefannica** [comment]
> If we have run all of these and checked it works, then im happy with it!

Yeah, I ran all of these on the local stack and they all work nicely.

**Pull request merged**
